# Generated by Django 5.0.2 on 2024-03-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brain',
            name='file',
            field=models.FileField(default='default/path/to/file', upload_to='brains/'),
        ),
    ]
