# Generated by Django 5.0.2 on 2024-03-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brain',
            name='file',
        ),
    ]
