# Generated by Django 3.2.23 on 2024-03-06 15:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=app.models.UploadToPathAndRename('brains/')),
        ),
    ]
